title: A GitHub Newbie Learning the Rope
author: RosaLS
email: rosastoddard78@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am totally new to GitHub. The reason why I want to learn how to use GitHub is because I want to develop an app or something like that.
# social links
twitter_username: lush_visions
github_username:  RosaLS
facebook_username: Rosa Stoddard

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
