title: Learning How to Use GitHub Pages with Jekyll
author: Rosa Stoddard
email: Rosastoddard78@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  So far I'm doing good. Still have a lot to learn before I am a pro.
  This is fun!

# social links
twitter_username: lush_visions
github_username:  RosaLS
facebook_username: Rosa Stoddard

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-time-machine
